version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
            - composer
        volumes:
            - ./public:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cranycrane
            MYSQL_DATABASE: diary
            MYSQL_USER: cranycrane
            MYSQL_PASSWORD: cranycrane
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db # Název hostitele databáze, odkazuje na službu 'db'
            PMA_USER: cranycrane # Uživatelské jméno pro přihlášení do phpMyAdmin
            PMA_PASSWORD: cranycrane # Heslo pro přihlášení do phpMyAdmin
        depends_on:
            - php-apache-environment
    composer:
        image: composer
        volumes:
          - ./public:/app
        working_dir: /app
        command: composer install
